@startuml
actor "Người dùng" as nd
participant "Phần mềm" as pm
participant "Quản lý\ndự án" as qlda
participant "Quản lý\nphòng ban" as qlpb
participant "Quản lý\nngười dùng" as qlnd
participant "Quản lý\nmilestone" as qlms
participant "Quản lý\nrelease" as qlrl
participant "Quản lý\nissue" as qlis
database "Project Table" as dbp

== Quy Trình Chỉnh sửa Phòng ban ==
nd -> pm : Gửi yêu cầu chỉnh sửa
pm -> qlda : Gửi yêu cầu chỉnh sửa
activate qlda
qlda -> qlda : Kiểm tra thông tin hợp lệ
alt Chỉnh sửa thành công
qlda -> dbp : Chỉnh sửa dữ liệu
dbp --> qlda : Xác nhận chỉnh sửa thành công
qlda --> pm : Xác nhận chỉnh sửa thành công
pm --> nd : Thông báo chỉnh sửa thành công
else Chỉnh sửa không thành công
qlda --> pm : Tên đã tồn tại
pm --> nd : Thông báo tên đã tồn lại
end
deactivate qlda
@enduml