@startuml
abstract class BaseEntity {
  +id: Long
  +createdAt: DateTime
  +updatedAt: DateTime
}

class Release {
  + name: String
  + code: String
  + description: String
  + startedDate: DateTime
  + releaseDate: DateTime
  + projectId: Long

  + create(createdData: Release)
  + update(updateData: Release)
  + delete(id: Long)
  + getReleaseInfo()
}
class Project {
  +name: String
  +code: String
  +description: String
}
BaseEntity <|-- Release
BaseEntity <|-- Project
Release "0..*" -- "1" Project : belongs to
@enduml